### ISSUE TITLE
Compile (issues) tracker

### ISSUE THREAD

**Issue by ghostrider-05** [ghostrider-05/RL-dummy-classes2#4]
- [ ] Unresolved class reference: 131 warnings
- [ ] Invalid property in default value: 239 warnings
- [ ] Unknown property in default value: 12 warnings
- [ ] Missing opening parenthesis: 22 warnings
- [ ] Unknown member: 114 warnings
- [x] other: 0 warnings

Total warnings: 468
